### Sign up new user
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"pass":"12345","profile":{"login":"Rouge","first_name":"Clar","last_name":"Mal","birth_date":{"Time":"1976-12-31T00:00:00Z","Valid":true},"gender":"female","city":"New York", "hobbies": ["C++"]}}' \
  http://localhost:8080/register

### Login
curl -u Batman123:12345 -X GET -H "Content-Type: application/json" http://localhost:8080/

### Get users list
curl -u Batman:12345 -X GET -H "Content-Type: application/json" http://localhost:8080/users

### Link friends
curl -u Superman:12345 --data "user=Rouge" http://localhost:8080/friend

### Get friends list
curl -u Rouge:12345 -X GET -H "Content-Type: application/json" http://localhost:8080/friends

### Get user
curl -u Batman:12345 -X GET -H "Content-Type: application/json" http://localhost:8080/user?user=Superman

### Unlink user
curl -u Superman:12345 --request PATCH --data "user=Rouge" http://localhost:8080/unfriend